version: "3.2"

volumes:
  jenkins_home:

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    restart: always
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /jenkins_home:/var/jenkins_home
    environment:
      - TZ=Asia/Seoul
